import { render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter } from "react-router-dom";
import { afterEach, describe, expect, it, vi } from "vitest";
import HomeManagementPage from "../HomeManagementPage";

function renderContacts(scenario = "success") {
  const suffix = scenario === "success" ? "" : `?scenario=${scenario}`;
  return render(<MemoryRouter initialEntries={[`/admin/home/contacts${suffix}`]}><HomeManagementPage /></MemoryRouter>);
}

afterEach(() => vi.restoreAllMocks());

describe("F2.2B contacts editor", () => {
  it("renders the direct contacts route", () => { renderContacts(); expect(screen.getByRole("heading", { level: 1, name: "Contatos públicos" })).toBeInTheDocument(); });
  it("loads every contact field from the deterministic mock", () => { renderContacts(); expect(screen.getByLabelText(/^E-mail institucional/)).toHaveValue("contato@sindgestao.org.br"); expect(screen.getByLabelText(/^Município/)).toHaveValue("Cuiabá"); expect(screen.getByLabelText(/^Unidade federativa/)).toHaveValue("MT"); });
  it("updates the footer preview from typed data", async () => { const user = userEvent.setup(); renderContacts(); const email = screen.getByLabelText(/^E-mail institucional/); await user.clear(email); await user.type(email, "novo@sindgestao.org.br"); expect(within(screen.getByRole("region", { name: "Contato no rodapé" })).getByText("novo@sindgestao.org.br")).toBeInTheDocument(); });
  it("masks a pasted postal code without blocking correction", async () => { const user = userEvent.setup(); renderContacts(); const postal = screen.getByLabelText(/^CEP/); await user.clear(postal); await user.click(postal); await user.paste("78123456"); expect(postal).toHaveValue("78123-456"); });
  it("masks a national phone", async () => { const user = userEvent.setup(); renderContacts(); const phone = screen.getByLabelText(/^Telefone público/); await user.clear(phone); await user.type(phone, "65999990000"); expect(phone).toHaveValue("(65) 99999-0000"); });
  it("omits an empty optional phone from preview", async () => { const user = userEvent.setup(); renderContacts(); await user.clear(screen.getByLabelText(/^Telefone público/)); expect(screen.queryByRole("link", { name: "(11) 1234-5678" })).not.toBeInTheDocument(); expect(screen.getByRole("region", { name: "Contato no rodapé" })).toBeInTheDocument(); });
  it("shows unsaved changes and clears them after save", async () => { const user = userEvent.setup(); renderContacts(); await user.type(screen.getByLabelText(/^Município/), " Centro"); expect(screen.getByText("Alterações não salvas")).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "Salvar rascunho" })); expect(await screen.findByText(/Rascunho salvo somente/)).toBeInTheDocument(); expect(screen.getByText("Sem alterações pendentes")).toBeInTheDocument(); });
  it("validates invalid email and focuses its input", async () => { const user = userEvent.setup(); renderContacts(); const email = screen.getByLabelText(/^E-mail institucional/); await user.clear(email); await user.type(email, "inválido"); await user.click(screen.getByRole("button", { name: "Salvar rascunho" })); expect(await screen.findByRole("alert")).toHaveTextContent("422"); await waitFor(() => expect(email).toHaveFocus()); });
  it("validates an invalid phone while preserving it", async () => { const user = userEvent.setup(); renderContacts(); const phone = screen.getByLabelText(/^Telefone público/); await user.clear(phone); await user.type(phone, "123"); await user.click(screen.getByRole("button", { name: "Salvar rascunho" })); expect(screen.getAllByText(/telefone nacional ou internacional válido/i).length).toBeGreaterThan(0); expect(phone).toHaveValue("(12) 3"); });
  it("requires street and municipality", async () => { const user = userEvent.setup(); renderContacts(); await user.clear(screen.getByLabelText(/^Logradouro/)); await user.clear(screen.getByLabelText(/^Município/)); await user.click(screen.getByRole("button", { name: "Salvar rascunho" })); expect(screen.getAllByText(/logradouro e número/i).length).toBeGreaterThan(0); expect(screen.getAllByText(/Informe um município/i).length).toBeGreaterThan(0); });
  it("rejects incomplete postal code", async () => { const user = userEvent.setup(); renderContacts(); const postal = screen.getByLabelText(/^CEP/); await user.clear(postal); await user.type(postal, "78000"); await user.click(screen.getByRole("button", { name: "Salvar rascunho" })); expect(screen.getAllByText(/exatamente 8 dígitos/i).length).toBeGreaterThan(0); });
  it("submits the entire contacts resource for review and locks editing", async () => { const user = userEvent.setup(); renderContacts(); await user.type(screen.getByLabelText(/^Município/), " Centro"); await user.click(screen.getByRole("button", { name: "Enviar para revisão" })); expect(await screen.findByText(/Configuração completa enviada/)).toBeInTheDocument(); expect(screen.getByText("Em revisão")).toBeInTheDocument(); expect(screen.getByLabelText(/^E-mail institucional/)).toBeDisabled(); });
  it("requires a cancellation reason", async () => { const user = userEvent.setup(); renderContacts(); await user.type(screen.getByLabelText(/^Município/), " Centro"); await user.click(screen.getByRole("button", { name: "Enviar para revisão" })); await user.click(await screen.findByRole("button", { name: "Cancelar envio" })); expect(screen.getByText(/pelo menos 10 caracteres/)).toBeInTheDocument(); await waitFor(() => expect(screen.getByLabelText("Motivo do cancelamento")).toHaveFocus()); });
  it("cancels a pending review and preserves no public version", async () => { const user = userEvent.setup(); renderContacts(); await user.type(screen.getByLabelText(/^Município/), " Centro"); await user.click(screen.getByRole("button", { name: "Enviar para revisão" })); await user.type(await screen.findByLabelText("Motivo do cancelamento"), "Corrigir o endereço antes da revisão."); await user.click(screen.getByRole("button", { name: "Cancelar envio" })); expect(await screen.findByText(/conteúdo voltou para rascunho/i)).toBeInTheDocument(); expect((await screen.findAllByText("Rascunho")).length).toBeGreaterThan(0); expect(screen.getAllByText("Nenhuma").length).toBeGreaterThan(0); });
  it("represents 401 without an editable form", () => { renderContacts("unauthenticated"); expect(screen.getByRole("alert")).toHaveTextContent("401"); expect(screen.queryByLabelText(/^E-mail institucional/)).not.toBeInTheDocument(); });
  it("represents 403 as readable and action-blocked", () => { renderContacts("forbidden"); expect(screen.getByRole("alert")).toHaveTextContent("403"); expect(screen.getByLabelText(/^E-mail institucional/)).toBeDisabled(); expect(screen.getByRole("button", { name: "Salvar rascunho" })).toBeDisabled(); });
  it("preserves local data after a simulated 409", async () => { const user = userEvent.setup(); renderContacts("conflict"); const email = screen.getByLabelText(/^E-mail institucional/); await user.clear(email); await user.type(email, "local@sindgestao.org.br"); await user.click(screen.getByRole("button", { name: "Salvar rascunho" })); expect(await screen.findByRole("alert")).toHaveTextContent("409"); expect(email).toHaveValue("local@sindgestao.org.br"); expect(screen.getByRole("button", { name: "Recarregar dados" })).toBeInTheDocument(); });
  it("maps server 422 to the email field without false success", async () => { const user = userEvent.setup(); renderContacts("validation"); const email = screen.getByLabelText(/^E-mail institucional/); await user.type(email, "x"); await user.click(screen.getByRole("button", { name: "Salvar rascunho" })); expect(await screen.findByRole("alert")).toHaveTextContent("422"); expect(screen.queryByText("Ação simulada concluída")).not.toBeInTheDocument(); expect(email).toHaveValue("contato@sindgestao.org.brx"); });
  it("represents unavailable and unexpected errors without internal details", () => { const first = renderContacts("unavailable"); expect(screen.getByRole("alert")).toHaveTextContent(/indisponível/i); first.unmount(); renderContacts("unexpected"); expect(screen.getByRole("alert")).toHaveTextContent(/Não foi possível/); });
  it("does not call fetch or browser storage", async () => { const fetchSpy = vi.spyOn(globalThis, "fetch"); const storageSpy = vi.spyOn(Storage.prototype, "setItem"); const user = userEvent.setup(); renderContacts(); await user.type(screen.getByLabelText(/^Município/), " Centro"); await user.click(screen.getByRole("button", { name: "Salvar rascunho" })); expect(fetchSpy).not.toHaveBeenCalled(); expect(storageSpy).not.toHaveBeenCalled(); });
});
