import { render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter } from "react-router-dom";
import { afterEach, describe, expect, it, vi } from "vitest";
import HomeManagementPage from "../HomeManagementPage";

function renderSocial(scenario = "success") {
  return render(<MemoryRouter initialEntries={[`/admin/home/social${scenario === "success" ? "" : `?scenario=${scenario}`}`]}><HomeManagementPage /></MemoryRouter>);
}
afterEach(() => vi.restoreAllMocks());

describe("F2.2B social editor", () => {
  it("renders the direct social route", () => { renderSocial(); expect(screen.getByRole("heading", { level: 1, name: "Redes sociais" })).toBeInTheDocument(); });
  it("loads the complete versioned configuration", () => { renderSocial(); expect(screen.getAllByText(/ID estável/)).toHaveLength(3); expect(screen.getByText("3 links configurados · 3 ativos")).toBeInTheDocument(); });
  it("adds the first unused platform with a stable draft id", async () => { const user = userEvent.setup(); renderSocial(); await user.click(screen.getByRole("button", { name: "Adicionar rede social" })); expect(screen.getByText("ID estável: social-draft-4")).toBeInTheDocument(); expect(screen.getByText("4 links configurados · 4 ativos")).toBeInTheDocument(); });
  it("rejects a duplicate platform including inactive items", async () => { const user = userEvent.setup(); renderSocial(); await user.selectOptions(screen.getAllByLabelText("Plataforma")[1]!, "Facebook"); await user.click(screen.getAllByRole("switch", { name: "Inativar Facebook" })[1]!); await user.click(screen.getByRole("button", { name: "Salvar rascunho" })); expect((await screen.findAllByText(/Plataforma duplicada|plataforma já é usada/i)).length).toBeGreaterThan(0); });
  it("accepts a valid official HTTPS URL", async () => { const user = userEvent.setup(); renderSocial(); const url = screen.getAllByLabelText("URL HTTPS")[0]!; await user.clear(url); await user.type(url, "https://facebook.com/sindgestao"); expect(screen.getByRole("link", { name: /Testar link de Facebook/ })).toHaveAttribute("href", "https://facebook.com/sindgestao"); });
  it.each(["http://facebook.com/sind", "javascript:alert(1)", "https://instagram.com/sind"])("rejects unsafe or incompatible URL %s", async (value) => { const user = userEvent.setup(); renderSocial(); const url = screen.getAllByLabelText("URL HTTPS")[0]!; await user.clear(url); await user.type(url, value); await user.click(screen.getByRole("button", { name: "Salvar rascunho" })); expect(await screen.findByRole("alert")).toHaveTextContent("422"); });
  it("moves an item down and normalizes the order", async () => { const user = userEvent.setup(); renderSocial(); await user.click(screen.getByRole("button", { name: "Mover Facebook para baixo" })); const items = screen.getAllByRole("listitem").filter((item) => item.textContent?.includes("ID estável")); expect(items[0]).toHaveTextContent("Instagram"); expect(items[1]).toHaveTextContent("Facebook"); });
  it("moves an item up using an accessible named control", async () => { const user = userEvent.setup(); renderSocial(); await user.click(screen.getByRole("button", { name: "Mover Instagram para cima" })); expect(screen.getByRole("button", { name: "Mover Instagram para cima" })).toBeDisabled(); });
  it("supports keyboard activation of ordering", async () => { const user = userEvent.setup(); renderSocial(); const button = screen.getByRole("button", { name: "Mover Instagram para cima" }); button.focus(); await user.keyboard("{Enter}"); expect(screen.getByRole("button", { name: "Mover Instagram para cima" })).toBeDisabled(); });
  it("inactivates a link without deleting it and removes it from preview", async () => { const user = userEvent.setup(); renderSocial(); await user.click(screen.getByRole("switch", { name: "Inativar Facebook" })); expect(screen.getByText("ID estável: facebook")).toBeInTheDocument(); expect(screen.queryByRole("link", { name: /^Facebook \(abre em nova aba\)$/ })).not.toBeInTheDocument(); expect(screen.getByRole("switch", { name: "Ativar Facebook" })).toHaveAttribute("aria-checked", "false"); });
  it("reactivates a link and restores it in preview", async () => { const user = userEvent.setup(); renderSocial(); await user.click(screen.getByRole("switch", { name: "Inativar Facebook" })); await user.click(screen.getByRole("switch", { name: "Ativar Facebook" })); expect(screen.getByRole("link", { name: /^Facebook \(abre em nova aba\)$/ })).toBeInTheDocument(); });
  it("removes only the draft item after confirmation and restores predictable focus", async () => { vi.spyOn(window, "confirm").mockReturnValue(true); const user = userEvent.setup(); renderSocial(); await user.click(screen.getByRole("button", { name: "Remover Facebook do rascunho" })); expect(screen.queryByText("ID estável: facebook")).not.toBeInTheDocument(); await waitFor(() => expect(screen.getByRole("button", { name: "Adicionar rede social" })).toHaveFocus()); });
  it("renders a useful empty preview with no orphan region", async () => { vi.spyOn(window, "confirm").mockReturnValue(true); const user = userEvent.setup(); renderSocial(); for (const name of ["Facebook", "Instagram", "YouTube"]) await user.click(screen.getByRole("button", { name: `Remover ${name} do rascunho` })); const preview = screen.getByRole("region", { name: "Redes sociais no rodapé" }); expect(within(preview).getByText("Nenhuma rede social ativa para exibir.")).toBeInTheDocument(); });
  it("protects preview and test links opened in a new tab", () => { renderSocial(); for (const link of screen.getAllByRole("link", { name: /abre em nova aba/ })) { expect(link).toHaveAttribute("target", "_blank"); expect(link).toHaveAttribute("rel", "noopener noreferrer"); } });
  it("saves the complete configuration only in memory", async () => { const user = userEvent.setup(); renderSocial(); await user.click(screen.getByRole("switch", { name: "Inativar Facebook" })); await user.click(screen.getByRole("button", { name: "Salvar rascunho" })); expect(await screen.findByText(/Rascunho salvo somente/)).toBeInTheDocument(); expect(screen.getByText("Sem alterações pendentes")).toBeInTheDocument(); });
  it("submits the complete configuration and locks all items", async () => { const user = userEvent.setup(); renderSocial(); await user.click(screen.getByRole("switch", { name: "Inativar Facebook" })); await user.click(screen.getByRole("button", { name: "Enviar para revisão" })); expect(await screen.findByText(/Configuração completa enviada/)).toBeInTheDocument(); expect(screen.getAllByLabelText("Plataforma")[0]).toBeDisabled(); expect(screen.getByRole("button", { name: "Cancelar envio" })).toBeInTheDocument(); });
  it("requires a cancellation reason and then returns the whole set to draft", async () => { const user = userEvent.setup(); renderSocial(); await user.click(screen.getByRole("switch", { name: "Inativar Facebook" })); await user.click(screen.getByRole("button", { name: "Enviar para revisão" })); await user.click(screen.getByRole("button", { name: "Cancelar envio" })); expect(screen.getByText(/pelo menos 10 caracteres/)).toBeInTheDocument(); await user.type(screen.getByLabelText("Motivo do cancelamento"), "Revisar os endereços das redes."); await user.click(screen.getByRole("button", { name: "Cancelar envio" })); expect(await screen.findByText(/voltou para rascunho/)).toBeInTheDocument(); expect(screen.getAllByText("Nenhuma").length).toBeGreaterThan(0); });
  it("represents 401 without exposing the configuration", () => { renderSocial("unauthenticated"); expect(screen.getByRole("alert")).toHaveTextContent("401"); expect(screen.queryByLabelText("Plataforma")).not.toBeInTheDocument(); });
  it("represents 403 in read-only mode", () => { renderSocial("forbidden"); expect(screen.getByRole("alert")).toHaveTextContent("403"); expect(screen.getAllByLabelText("Plataforma")[0]).toBeDisabled(); });
  it("maps server 422 to the first item and preserves edits", async () => { const user = userEvent.setup(); renderSocial("validation"); await user.click(screen.getByRole("switch", { name: "Inativar Facebook" })); await user.click(screen.getByRole("button", { name: "Salvar rascunho" })); expect(await screen.findByRole("alert")).toHaveTextContent("422"); expect(screen.getByRole("switch", { name: "Ativar Facebook" })).toBeInTheDocument(); expect(screen.queryByText("Ação simulada concluída")).not.toBeInTheDocument(); });
  it("preserves the configuration on conflict and offers reload", async () => { const user = userEvent.setup(); renderSocial("conflict"); await user.click(screen.getByRole("switch", { name: "Inativar Facebook" })); await user.click(screen.getByRole("button", { name: "Salvar rascunho" })); expect(await screen.findByRole("alert")).toHaveTextContent("409"); expect(screen.getByRole("switch", { name: "Ativar Facebook" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Recarregar dados" })).toBeInTheDocument(); });
  it("represents loading, empty, unavailable and unexpected states", () => { for (const [scenario, expected] of [["loading", "Carregando redes sociais"], ["empty", "Nenhum conteúdo configurado"], ["unavailable", "indisponível"], ["unexpected", "Não foi possível"]] as const) { const view = renderSocial(scenario); expect(document.body).toHaveTextContent(expected); view.unmount(); } });
  it("does not call fetch or storage", async () => { const fetchSpy = vi.spyOn(globalThis, "fetch"); const storageSpy = vi.spyOn(Storage.prototype, "setItem"); const user = userEvent.setup(); renderSocial(); await user.click(screen.getByRole("switch", { name: "Inativar Facebook" })); await user.click(screen.getByRole("button", { name: "Salvar rascunho" })); expect(fetchSpy).not.toHaveBeenCalled(); expect(storageSpy).not.toHaveBeenCalled(); });
});
